// DO NOT EDIT - generated by github.com/edwarnicke/imports-gen
package imports

import (
	_ "context"
	_ "github.com/antonfisher/nested-logrus-formatter"
	_ "github.com/kelseyhightower/envconfig"
	_ "github.com/networkservicemesh/sdk-k8s/pkg/registry/chains/registryk8s"
	_ "github.com/networkservicemesh/sdk-k8s/pkg/tools/k8s"
	_ "github.com/networkservicemesh/sdk/pkg/tools/debug"
	_ "github.com/networkservicemesh/sdk/pkg/tools/grpcutils"
	_ "github.com/networkservicemesh/sdk/pkg/tools/jaeger"
	_ "github.com/networkservicemesh/sdk/pkg/tools/log"
	_ "github.com/networkservicemesh/sdk/pkg/tools/signalctx"
	_ "github.com/networkservicemesh/sdk/pkg/tools/spanhelper"
	_ "github.com/sirupsen/logrus"
	_ "github.com/spiffe/go-spiffe/v2/spiffetls/tlsconfig"
	_ "github.com/spiffe/go-spiffe/v2/workloadapi"
	_ "google.golang.org/grpc"
	_ "google.golang.org/grpc/credentials"
	_ "net/url"
	_ "os"
	_ "time"
)
